services:
  web:
    container_name: php_courteline
    build: .
    volumes:
      - "./:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/30-custom.ini"
    depends_on:
      - db_courteline
    ports:
      - "80:80"

  db_courteline:
    container_name: db_courteline
    image: mysql:9
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - "./database/db_dev.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
      - "./db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
