services:
  web:
    container_name: php_courteline
    build: .
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
    ports:
      - "80:80"

  db:
    container_name: db
    image: mysql:9
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - "./db_data:/var/lib/mysql"
    ports:
      - "3306:3306"
